#!/bin/bash

DEFAULT_LANG="es"
NOT_AUTHENTICATED_TABS_HIDDEN="true"
NOT_AUTHENTICATED_FULL_SCREEN="true"
MEMORY_CACHE_DEFAULT_TTL="60"
GEOLOCATION_UPDATE_INTERVAL="150"
ALWAYS_SHOW_INTRO="false"
GRAVATAR_DEFAULT="retro"
GRAVATAR_SIZE="200"
PRODUCTION="true"
INTRO_SLIDES=""

source ./parameters.config

sed \
-e "s/%APP_NAME_FULL%/$APP_NAME_FULL/g" \
-e "s/%APP_VENDOR%/$APP_VENDOR/g" \
-e "s/%APP_NAME%/$APP_NAME/g" \
-e "s/%APP_VERSION%/$APP_VERSION/g" \
-e "s/%APP_NAME_DESCRIPTION%/$APP_NAME_DESCRIPTION/g" \
-e "s/%API_KEY_FOR_ANDROID%/$API_KEY_FOR_ANDROID/g" \
-e "s/%API_KEY_FOR_IOS%/$API_KEY_FOR_IOS/g" \
-e "s/%LOCATION_IN_USE_USAGE_DESCRIPTION%/$LOCATION_IN_USE_USAGE_DESCRIPTION/g" \
-e "s/%LOCATION_ALWAYS_USAGE_DESCRIPTION%/$LOCATION_ALWAYS_USAGE_DESCRIPTION/g" \
-e "s/%CALENDAR_USAGE_DESCRIPTION%/$CALENDAR_USAGE_DESCRIPTION/g" \
-e "s/%MAIN_COLOR%/$MAIN_COLOR/g" \
-e "s/%FACEBOOK_APP_ID%/$FACEBOOK_APP_ID/g" \
-e "s/%FACEBOOK_APP_NAME%/$FACEBOOK_APP_NAME/g" \
config.xml.template > config.xml

sed \
-e "s/%APP_NAME_FULL%/$APP_NAME_FULL/g" \
-e "s/%APP_VENDOR%/$APP_VENDOR/g" \
-e "s/%APP_NAME%/$APP_NAME/g" \
-e "s/%APP_VERSION%/$APP_VERSION/g" \
-e "s/%APP_NAME_DESCRIPTION%/$APP_NAME_DESCRIPTION/g" \
-e "s/%API_KEY_FOR_ANDROID%/$API_KEY_FOR_ANDROID/g" \
-e "s/%API_KEY_FOR_IOS%/$API_KEY_FOR_IOS/g" \
-e "s/%LOCATION_IN_USE_USAGE_DESCRIPTION%/$LOCATION_IN_USE_USAGE_DESCRIPTION/g" \
-e "s/%LOCATION_ALWAYS_USAGE_DESCRIPTION%/$LOCATION_ALWAYS_USAGE_DESCRIPTION/g" \
-e "s/%CALENDAR_USAGE_DESCRIPTION%/$CALENDAR_USAGE_DESCRIPTION/g" \
-e "s/%MAIN_COLOR%/$MAIN_COLOR/g" \
-e "s/%FACEBOOK_APP_ID%/$FACEBOOK_APP_ID/g" \
-e "s/%FACEBOOK_APP_NAME%/$FACEBOOK_APP_NAME/g" \
package.json.template > package.json


APP_CONFIG=$(cat <<-END
export const CONFIG_ENV = {
    PRODUCTION: $PRODUCTION,
    API_URL : "$API_URL",
    APP_NAME : "$APP_NAME_FULL",
    DEFAULT_LANG: "$DEFAULT_LANG",
    ANDROID_PUSH_ICON_COLOR: "$MAIN_COLOR",
    NOT_AUTHENTICATED_TABS_HIDDEN: $NOT_AUTHENTICATED_TABS_HIDDEN,
    NOT_AUTHENTICATED_FULL_SCREEN: $NOT_AUTHENTICATED_FULL_SCREEN,
    MEMORY_CACHE_DEFAULT_TTL: $MEMORY_CACHE_DEFAULT_TTL,
    GEOLOCATION_UPDATE_INTERVAL: $GEOLOCATION_UPDATE_INTERVAL,
    ALWAYS_SHOW_INTRO: $ALWAYS_SHOW_INTRO,
    GRAVATAR_DEFAULT: '$GRAVATAR_DEFAULT',
    GRAVATAR_SIZE: '$GRAVATAR_SIZE',
    INTRO_SLIDES: [ $INTRO_SLIDES ]
}
END
)

echo $APP_CONFIG > src/config/config.dev.ts

npm i

echo "* $APP_NAME_FULL: Configurada !"
