export const CONFIG_ENV = {
    PRODUCTION: true,
    API_URL : "http://localhost:8800/",
    DEFAULT_LANG: "es",
    FIREBASE_SENDER_ID: "",
    FIREBASE_APP_ID: "",
    NOT_AUTHENTICATED_TABS_HIDDEN: true,
    NOT_AUTHENTICATED_FULL_SCREEN: true,
    MEMORY_CACHE_DEFAULT_TTL: 30
}